name: tgt
on:
  workflow_dispatch:
    inputs:
      extra_args:
        required: false
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        t: [aarch64-linux-android]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.t }}
      - name: Install NDK tool
        run: cargo install cargo-ndk
      - name: Compile
        env:
          ALSA_NO_PKG_CONFIG: '1'
          ALSA_STATIC: '1'
        run: |
          ARGS="${{ github.event.inputs.extra_args }}"
          if [[ "${{ matrix.t }}" == *musl* && -z "$ARGS" ]]; then
            ARGS="--no-default-features --features static-download"
          fi
          if [[ "${{ matrix.t }}" == *"android"* ]]; then
            cargo ndk --target ${{ matrix.t }} --android-platform 24 build --release --locked $ARGS
          else
            cargo build --target ${{ matrix.t }} --release --locked $ARGS
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: tgt-${{ matrix.t }}
          path: target/${{ matrix.t }}/release/tgt
